# PATHS
package_path: /home/mario/jobs/AutoDFTB
dftb_bin_path: /home/mario/app/dftbplus/bin/dftb+
slakos:  /home/mario/app/dftbplus/slakos/from_cp2k/scc

xyz_dir: ${package_path}/val_data/dftb/xyz_files_fixed_opt
poscar_dir: ${package_path}/val_data/dftb/poscar_files
json_dir: ${package_path}/val_data/dftb/json_files
working_dir: ${package_path}/tmp

# BOX SIZE
periodic: True
box_size: [39.53476932, 0.0, 0.0, 0.0, 34.27629786, 0.0, 0.0, 0.0, 10.0]

# DFTB
optimize_geometry: False
charge: 0
max_iterations: 200
max_steps: 100
fermi_temperature: 1000.0
scc: True
spin_polarization: True
scctolerance: 1e-10

# SLURM
slurm_job_name: DFTB_DG
slurm_mem:
slurm_ncpus: 16
slurm_nodelist:
slurm_partition: long
slurm_timeout: 2800
slurm_output: outputs/slurm_out
slurm_exclude:

# VERBOSITY
verbose: True
scheduler: slurm