# PATHS
package_path: /home/mario/jobs/AutoDFTB
dftb_bin_path: /home/mario/app/dftbplus/bin/dftb+
slakos:  /home/mario/app/dftbplus/slakos/pbc-0-3
working_dir: ${package_path}/tmp

xyz_dir: ${package_path}/test_batch/xyz_files_fixed
xyz_dir_fixed: ${package_path}/test_batch/dftb/xyz_files_fixed_opt

# BOX SIZE
periodic: True
box_size: [39.53476932, 0.0, 0.0, 0.0, 34.27629786, 0.0, 0.0, 0.0, 10.0]
bond_lenght: 1.42
delta_x: 0.4
delta_y: 0.4
delta_interface: 1.88

#DFTB for Geometry Optimization
optimize_geometry: True
optimize_lattice: False
max_steps: 200
remove_if_not_converged: True

# SLURM
slurm_job_name: OptGeom_DG
slurm_mem:
slurm_ncpus: 16
slurm_nodelist:
slurm_partition: long
slurm_timeout: 2800
slurm_output: outputs/slurm_out
slurm_exclude:

# VERBOSITY
verbose: True

scheduler: slurm