# PATHS
package_path: /home/tommaso/git_workspace/AutoDFTB

xyz_dir: ${package_path}/data/transport/devices
json_dir: ${package_path}/data/transport/transport_output
out_dir: ${package_path}/data/transport/stm_images_new

# STM
#fermi_energy: -4.62
bias: 0.35
resolution: 256
tau: 5
scan_h: 1
save_npy: False
save_png: True

# SLURM
slurm_job_name: Graphene_STM
slurm_mem:
slurm_ncpus: 16
slurm_nodelist:
slurm_partition: long
slurm_timeout: 2800
slurm_output: outputs/slurm_out
slurm_exclude:

# VERBOSITY
verbose: True
