# PATHS
package_path: /home/tommaso/git_workspace/AutoDFTB
dftb_bin_path: /home/tommaso/Applications/dftbplus/bin/dftb+
slakos: /home/tommaso/Applications/dftbplus/slakos/pbc-0-3
setupgeom_bin_path: /home/tommaso/Applications/dftbplus/bin/setupgeom
working_dir: ${package_path}/tmp

electrodes_dir: ${package_path}/data_new/transport/electrodes
gen_dir: ${package_path}/data_new/transport/gen_files
transport_output: ${package_path}/data_new/transport/transport_output

# BOX SIZE
periodic: True
box_size: [65.0, 0.0, 0.0, 0.0, 34.27629786, 0.0, 0.0, 0.0, 40.0]

# ELECTRODE
electrode_cell:
  [7.409367073373903, 0.0, 0.0, 0.0, 34.27629786, 0.0, 0.0, 0.0, 10.0]

#SETUPGEOM
plsdefined: 1

#CONTACT
fermi_temperature: 0.0

#TRANSPORT
scc: False
max_iterations: 200
task: UploadContacts
potential_source: 0.05
potential_drain: -0.05
tunnelinganddos:
  verbosity: 100
  offset_energy_range: 0.5
  resolution: 100
  compute_regions: True

#STM
compute_stm: False
bias: 0.35
resolution: 256
tau: 5
scan_h: 1
stm_output: ${package_path}/data_new/transport/stm_images
xyz_dir: ${package_path}/data_new/transport/electrodes
save_npy: False
save_png: True

# SLURM
slurm_job_name: Transport_G
slurm_mem:
slurm_ncpus: 16
slurm_nodelist:
slurm_partition: long
slurm_timeout: 2800
slurm_output: outputs/slurm_out
slurm_exclude:

# VERBOSITY
verbose: True
